# Build settings
markdown: kramdown
highlighter: pygments
gems:
  - jemoji
  
# Site settings
title: "dandel"
description: Software Craftsman apprentice

email: mail@dandel.es
#blog logo
logo: "/assets/images/logo.jpg"
# blog cover
cover: "/assets/images/blog-cover.jpg"

name: 'Daniel de la Cruz'
author: 'Daniel de la Cruz'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "https://blog.dandel.es" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@dandel'

#fill in disqus shortname to use disqus
disqus: disqus_IGCcPhET0I

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/dandel
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	github
    url:	https://github.com/danderu
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:
